In [143]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import create_engine, text
import os

In [ ]:
%pip install sqlalchemy psycopg2-binary

In [ ]:
Database_url = "postgresql://neondb_owner:npg_qStXmZLBQ5A9@ep-wispy-sunset-axezqxvm-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
engine = create_engine(Database_url)

In [ ]:
engine = create_engine(
    Database_url,
    poolclass = None,
    connect_args = {
        "sslmode": "require",
        "connect_timeout": 10
    }
)
try:
    with engine.connect() as connection:
        result = connection.execute(text("SELECT 1"))
        print("Connection successful:", result.fetchone())
        print("Connection successful")

except Exception as e:
    print("Connection failed:", e)

Connection successful: (1,)
Connection successful

In [ ]:
Query = """
SELECT table_name
FROM Information_schema.tables
WHERE table_schema = 'public'
"""

tables = pd.read_sql(Query, engine)
tables

       table_name
0        bookings
1          guests
2          hotels
3         reviews
4  clean_bookings

### LOAD THE HOTEL DATASET

In [ ]:
hotel_detail = pd.read_sql("SELECT * FROM hotels", engine)
hotel_detail.head()

   hotel_id            hotel_name    location  star_rating  total_rooms
0         1  The Birmingham Grand  Birmingham            4          254
1         2   The London Heritage      London            5          234
2         3   The Oxford Boutique      Oxford            3          146
3         4  The Glasgow Heritage     Glasgow            3           84
4         5  Glasgow Metropolitan     Glasgow            4          214

In [ ]:
hotel_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   hotel_id     25 non-null     int64
 1   hotel_name   25 non-null     object
 2   location     25 non-null     object
 3   star_rating  25 non-null     int64
 4   total_rooms  25 non-null     int64
dtypes: int64(3), object(2)
memory usage: 1.1+ KB

In [ ]:
booking_detail = pd.read_sql("SELECT * FROM bookings", engine)
booking_detail.head()

,booking_id,guest_id,hotel_id,room_type,booking_channel,check_in_date,check_out_date,total_amount,stay_duration
0,1,6699,18,Suite,Direct Website,2025-05-25,2025-05-26,296.44,1
1,2,11380,23,Deluxe,Corporate Portal,2025-01-09,2025-01-13,483.56,4
2,3,4812,13,Executive,Travel Agent,2025-03-04,2025-03-06,415.59,2
3,4,982,12,Family Room,Airbnb,2026-03-06,2026-03-09,601.18,3
4,5,615,5,Deluxe,Expedia,2025-02-25,2025-03-02,603.85,5

In [ ]:
booking_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   booking_id       35000 non-null  int64
 1   guest_id         35000 non-null  int64
 2   hotel_id         35000 non-null  int64
 3   room_type        35000 non-null  object
 4   booking_channel  35000 non-null  object
 5   check_in_date    35000 non-null  object
 6   check_out_date   35000 non-null  object
 7   total_amount     35000 non-null  float64
 8   stay_duration    35000 non-null  int64
dtypes: float64(1), int64(4), object(4)
memory usage: 2.4+ MB

In [ ]:
guest_detail = pd.read_sql("SELECT * FROM guests", engine)
guest_detail.head()

   guest_id customer_type loyalty_status               country  previous_stays
0         1       Leisure           None             Australia               0
1         2       Leisure           None               Germany               1
2         3      Business           Gold        United Kingdom               0
3         4        Family         Silver  United Arab Emirates               8
4         5     Corporate           None                France               0

In [ ]:
guest_detail.isnull().sum()

guest_id             0
customer_type        0
loyalty_status    6036
country              0
previous_stays       0
dtype: int64

In [ ]:
guest_detail.isnull().sum()
guest_detail['loyalty_status'] = guest_detail['loyalty_status'].fillna('No_loyalty_status')

In [ ]:
guest_detail.head()

,guest_id,customer_type,loyalty_status,country,previous_stays
0,1,Leisure,No_loyalty_status,Australia,0
1,2,Leisure,No_loyalty_status,Germany,1
2,3,Business,Gold,United Kingdom,0
3,4,Family,Silver,United Arab Emirates,8
4,5,Corporate,No_loyalty_status,France,0

In [ ]:
review_detail = pd.read_sql("SELECT * FROM reviews", engine)
review_detail.head(5)

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral
1,2,2,11380,23,The room was nothing out of the ordinary for w...,4.0,2025-01-22,positive
2,3,3,4812,13,"Unfortunately, the pool was outdated — it clea...",1.9,2025-03-13,negative
3,4,4,982,12,We were disappointed that the neighborhood was...,2.2,2026-03-18,negative
4,5,5,615,5,The room service was standard hotel fare for w...,3.3,2025-03-03,neutral

In [ ]:
review_detail.isnull().sum()

review_id          0
booking_id         0
guest_id           0
hotel_id           0
review_text        0
rating_score       0
review_date        0
sentiment_label    0
dtype: int64

In [ ]:
clean_booking_detail = pd.read_sql("SELECT * FROM clean_bookings", engine)
clean_booking_detail.head(5)

,booking_id,guest_id,hotel_id,room_type,booking_channel,check_in_date,check_out_date,total_amount,stay_duration
0,1,6699,18,Suite,Direct Website,2025-05-25,2025-05-26,296.44,1
1,2,11380,23,Deluxe,Corporate Portal,2025-01-09,2025-01-13,483.56,4
2,3,4812,13,Executive,Travel Agent,2025-03-04,2025-03-06,415.59,2
3,4,982,12,Family Room,Airbnb,2026-03-06,2026-03-09,601.18,3
4,5,615,5,Deluxe,Expedia,2025-02-25,2025-03-02,603.85,5

In [ ]:
clean_booking_detail.isnull().sum()

booking_id         0
guest_id           0
hotel_id           0
room_type          0
booking_channel    0
check_in_date      0
check_out_date     0
total_amount       0
stay_duration      0
dtype: int64

In [ ]:
clean_booking_detail['check_in_date'] = pd.to_datetime(clean_booking_detail['check_in_date'])
clean_booking_detail['check_out_date'] = pd.to_datetime(clean_booking_detail['check_out_date'])
clean_booking_detail.head()
clean_booking_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   booking_id       35000 non-null  int64
 1   guest_id         35000 non-null  int64
 2   hotel_id         35000 non-null  int64
 3   room_type        35000 non-null  object
 4   booking_channel  35000 non-null  object
 5   check_in_date    35000 non-null  datetime64[ns]
 6   check_out_date   35000 non-null  datetime64[ns]
 7   total_amount     35000 non-null  float64
 8   stay_duration    35000 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(4), object(2)
memory usage: 2.4+ MB

In [ ]:
booking_detail['check_in_date'] = pd.to_datetime(booking_detail['check_in_date'])
booking_detail['check_out_date'] = pd.to_datetime(booking_detail['check_out_date'])
booking_detail.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35000 entries, 0 to 34999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   booking_id       35000 non-null  int64
 1   guest_id         35000 non-null  int64
 2   hotel_id         35000 non-null  int64
 3   room_type        35000 non-null  object
 4   booking_channel  35000 non-null  object
 5   check_in_date    35000 non-null  datetime64[ns]
 6   check_out_date   35000 non-null  datetime64[ns]
 7   total_amount     35000 non-null  float64
 8   stay_duration    35000 non-null  int64
dtypes: datetime64[ns](2), float64(1), int64(4), object(2)
memory usage: 2.4+ MB

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots
from plotly.subplots import make_subplots

In [ ]:
merge = review_detail.merge(booking_detail, on=['booking_id', 'guest_id', 'hotel_id'], how='inner')
merge = merge.merge(guest_detail, on='guest_id', how='inner')
merge = merge.merge(hotel_detail, on='hotel_id', how='inner')

In [ ]:
### ROOM TYPE DISTRIBUTION
room_type = booking_detail['room_type'].value_counts().reset_index()
room_type.columns = ['room_type', 'count']
room_type

### ROOM REVENUE BY ROOM TYPE
room_revenue = booking_detail.groupby('room_type')['total_amount'].sum().reset_index()
room_revenue.columns = ['room_type', 'total_revenue']

#### BOOKING CHANNEL DISTRIBUTION
channels = booking_detail['booking_channel'].value_counts().reset_index()
channels

#### BOOKING CHANNEL REVENUE
channel_revenue = booking_detail.groupby('booking_channel')['total_amount'].sum().reset_index()
channel_revenue

fig = make_subplots(rows=2, cols=2, subplot_titles=('Room Type by Distribution', 'Room Revenue by Room Type','Channel Distribution','Total Revenue by Booking Channel'))
fig.add_trace(go.Bar(x=room_type['room_type'], y=room_type['count'], name='Room Type Distribution'), row=1, col=1)
fig.add_trace(go.Bar(x=room_revenue['room_type'], y=room_revenue['total_revenue'], name='Room Revenue by Room Type'), row=1, col=2)
fig.add_trace(go.Bar(x=channels['booking_channel'], y=channels['count'], name='Channel Distribution'), row=2, col=1)
fig.add_trace(go.Bar(x=channel_revenue['booking_channel'], y=channel_revenue['total_amount'], name='Channel Revenue'), row=2, col=2)

fig.update_layout(title_text='Booking Analysis', height=800, width=1000)
fig.show()

In [ ]:
merge.head()

,review_id,booking_id,guest_id,hotel_id,review_text,rating_score,review_date,sentiment_label,room_type,booking_channel,...,total_amount,stay_duration,customer_type,loyalty_status,country,previous_stays,hotel_name,location,star_rating,total_rooms
0,1,1,6699,18,The overall price was fair for what we paid. M...,3.2,2025-06-02,neutral,Suite,Direct Website,...,296.44,1,Leisure,No_loyalty_status,France,4,The Aberdeen Grand,Aberdeen,4,118
1,3266,3266,9241,18,"Overall the check-in process was standard, abo...",2.7,2025-10-29,neutral,Deluxe,Booking.com,...,549.75,3,Business,Silver,United Kingdom,6,The Aberdeen Grand,Aberdeen,4,118
2,20019,20019,11891,18,"The front desk team was adequate, nothing more...",2.5,2025-03-19,neutral,Twin,Booking.com,...,363.10,3,Corporate,No_loyalty_status,United Kingdom,2,The Aberdeen Grand,Aberdeen,4,118
3,31706,31706,11891,18,This hotel made our time in Aberdeen truly mem...,3.7,2025-09-14,positive,Standard,Expedia,...,607.83,7,Corporate,No_loyalty_status,United Kingdom,2,The Aberdeen Grand,Aberdeen,4,118
4,33078,33078,5469,18,"Overall the check-in desk was acceptable, abou...",2.6,2025-04-14,neutral,Deluxe,Travel Agent,...,660.28,4,Leisure,Silver,Netherlands,0,The Aberdeen Grand,Aberdeen,4,118

In [ ]:
merge.to_csv("../data/processed/merged_data.csv", index=False)
print("Shape:", merge.shape)

Shape: (35000, 22)

In [ ]:
os.makedirs("data/processed", exist_ok=True)

# Save hotels
hotel_detail.to_csv(r"data/processed/hotel_detail.csv", index=False)

# Save bookings
booking_detail.to_csv(r"data/processed/booking_detail.csv", index=False)

# Save guests
guest_detail.to_csv(r"data/processed/guest_detail.csv", index=False)

# Save reviews
review_detail.to_csv(r"data/processed/review_detail.csv", index=False)

# Save clean bookings
clean_booking_detail.to_csv(r"data/processed/clean_booking_detail.csv", index=False)